### ISSUE TITLE
Failed to install on Ubuntu 12.04 precise 32bit

### ISSUE THREAD

**Issue by kipanshi** [dreamhost/httplib2-ca_certs_locater#2]
Hi,

after doing::

```
pip install httplib2.ca_certs_locater
```

I get import error if I try to import `ca_certs_locater`::

```
import ca_certs_locater
```

Also I cannot find this file in ve/lib/python2.7/site-packages/

Seems that the installation script doesn's install the `ca_certs_locater.py` file.

**Comment by kipanshi** [comment]
Python 2.7.3 (default, Sep 26 2013, 20:08:41) 
[GCC 4.6.3] on linux2

**Comment by kipanshi** [comment]
Output of `pip freeze`::

```
argparse==1.2.1
distribute==0.6.24
httplib2==0.8
httplib2.ca-certs-locater==0.1.0
ipdb==0.8
ipython==1.1.0
oauth2==1.5.211
python-odesk==0.5
urllib3==1.7.1
wsgiref==0.1.2
```

**Comment by kipanshi** [comment]
Upgrading to `distribute==0.7.3` does not solve the problem either.

**Comment by dhellmann** [comment]
Distribute has been merged back into setuptools. Try installing the latest setuptools and then installing this library.

**Comment by kipanshi** [comment]
I've done::

```
sudo pip install setuptools --upgrade 
```

then created new virtualenvironment, installed the library and still get `ImportError`

**Comment by dhellmann** [comment]
What version of setuptools is installed in the virtualenv? Usually to update that, you have to upgrade pip and virtualenv. Also, please make sure distribute is not being used in the virtualenv.

**Comment by kipanshi** [comment]
Still get `ImportError`. Here's the list of installed packages into virtualenv::

```
Python          - 2.7.3        - active development (/usr/lib/python2.7/lib-dynload)
argparse        - 1.2.1        - active development (/usr/lib/python2.7)
distribute      - 0.7.3        - active 
httplib2.ca-certs-locater - 0.1.0        - active 
httplib2        - 0.8          - active 
ipdb            - 0.8          - active 
ipython         - 1.1.0        - active 
oauth2          - 1.5.211      - active 
pip             - 1.1          - active 
python-odesk    - 0.5          - active 
setuptools      - 1.1.7        - active 
urllib3         - 1.7.1        - active 
wsgiref         - 0.1.2        - active development (/usr/lib/python2.7)
yolk            - 0.4.3        - active
```

**Comment by kipanshi** [comment]
Is it possible to make lib compatible with old setuptools, i. e. utilize `setup.py` and distutils? I just don't want to upload yet another package to Pypi, this is a useful lib.
